apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: status-api
    newName: 611651385461.dkr.ecr.ap-south-1.amazonaws.com/devops-mcp-status-api
    newTag: v1
