apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: status-api
    newName: 295932822549.dkr.ecr.ap-south-1.amazonaws.com/devops-mcp-status-api
    newTag: latest
