apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: status-api
    newName: ghcr.io/chavanakash/devops-mcp-status-api
    newTag: v1
